version: '2.1'
volumes:
  whisper:
    driver: local
services:
  carbon:
    image: passy/rpi-docker-carbon-whisper
    volumes:
    - whisper:/opt/graphite/storage/whisper
    - ./carbon-whisper/conf:/opt/graphite/conf:ro
    ports:
    - "2003-2004:2003-2004"
  graphite:
    image: passy/rpi-docker-graphite-api
    volumes:
    - whisper:/opt/graphite/storage/whisper
    - ./graphite-api/graphite-api.yaml:/etc/graphite-api.yaml:ro
    links:
    - carbon
