version: '2.1'
volumes:
  whisper:
    driver: local
services:
  carbon:
    build: ./carbon-whisper
    image: passy/rpi-docker-carbon-whisper
    volumes:
      - whisper:/opt/graphite/storage/whisper
      - ./carbon-whisper/conf:/opt/graphite/conf:ro
  graphite:
    build: ./graphite-api
    image: passy/rpi-docker-graphite-api
    volumes:
      - whisper:/opt/graphite/storage/whisper
      - ./graphite-api/graphite-api.yaml:/etc/graphite-api.yaml:ro
    links:
      - carbon
    ports:
      - "8080:8080"
  statsd:
    build: ./statsd
    image: passy/rpi-docker-statsd
    volumes:
    - ./statsd/config.js:/statsd/config.js:ro
    links:
    - carbon
    ports:
    - "8125:8125/udp"
